openapi: 3.0.1
info:
  title: DGC Verifier Service API
  description: The API defines how to exchange verification information for the Digital Green Certificates.
  version: 1.0.0
servers:
  - url: 'http://localhost:9080'
    description: Generated server url
paths:
  /v1/dgc/signercertificate/update:
    get:
      tags:
        - Signer Information
      summary: Gets one signer certificate.
      operationId: getSignerCertificateUpdate
      parameters:
        - name: X-RESUME-TOKEN
          in: header
          description: Defines where to resume the download of the certificates
          required: false
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Returns a filtered list of trusted certificates.
          content:
            text/plain:
              schema:
                type: string
              example: MIIBGzCBwqADAgECAgRggUObMAoGCCqGSM49BAMCMBYxFDASBgNVBAMMC2VkZ2NfZGV2X2VjMB4XDTIxMDQyMjA5MzYyN1oXDTIyMDQyMjA5MzYyN1owFjEUMBIGA1UEAwwLZWRnY19kZXZfZWMwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQVQc9JY190s/Jn0CBSq/AWuxmqUzRVu+AsCe6gfbqk3s0e4jonzp5v/5IMW/9t7v5Fu2ITMmOTVfKL1TuM+aixMAoGCCqGSM49BAMCA0gAMEUCIQCGWIk6ZET3afRxdpFVuXdrEYtFiR1MGDx4HweZfspjSgIgBdCJsT746/FI3euIbzKDoeY65m+Qx2/4Cd/vOayNbuw=
        '204':
          description: No Content available. All certificates already downloaded.
  /v1/dgc/signercertificate/status:
    get:
      tags:
        - Signer Information
      summary: Gets list of kids from all valid certificates.
      operationId: getSignerCertificateStatus
      responses:
        '200':
          description: Returns a filtered list of trusted certificates.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
              example:
                - 8xYtW2837bc=
                - zoQi+KT68LM=
  /v1/dgc/settings:
    get:
      tags:
        - Settings
      summary: Gets list of italian business rules and other settings.
      operationId: getSettings
      responses:
        '200':
          description: Returns a list of settings.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SettingEntity'
              example:
                - name: vaccine_start_day
                  type: VACCINE1
                  value: '15'
                - name: vaccine_end_day
                  type: VACCINE1
                  value: '180'
components:
  schemas:
    SettingEntity:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
        value:
          type: string
